# last updated by SSDDeployer utility...
# Sat Jun 14 16:15:25 IST 2025
# THIS IS A SAMPLE - ADD REMOVE TOKENS PER PROJECT
%%TARGET%%=example
#DB Type
%%DBTYPE%%=mysql
#######################################################
# Exchange / Email Information
#######################################################
%%EXCHANGE_SERVER%%=server1.example.com
%%FROM_ADDRESS%%=&amp;support@example.com
%%REPLY_TO_ADDRESS%%=&amp;support@example.com
%%SERVER_HOST%%=server2.example.com
#######################################################
# AIX Connectors
#######################################################
%%AIX_BRC_NAME%%=Unix Host
%%AIX_BRC_HOST%%=server3
%%AIX_BRC_PASSWORD%%=myencryptedpasswordstring
#######################################################
# AD Connectors
#######################################################
%%AD_HOST%%=example.com
%%AD_PORT%%=389
%%AD_PROXY_USER%%=CN\=administrator,OU\=Users,DC\=example,DC\=com
%%AD_PROXY_PASSWORD%%=myencryptedpasswordstring
# A more complex token example showing a multi-line token that includes XML.
# End each line with backslash "\" to mark it for continuation.
#%%AD_SERVER_LIST%%=<List>\
#<String>server1.domain.com</String>\
#<String>server2.domain.com</String>\
#<String>server3.domain.com</String>\
#</List>
# Properties file for environment specific build tokens
# THIS IS A SAMPLE - ADD REMOVE TOKENS PER PROJECT
%%TARGET%%=example
#DB Type
%%DBTYPE%%=mysql
#***********************************************************************************
# FRAMEWORK PROPERTIES
#***********************************************************************************
#***********************************************************************************
# 	ROLE ASSIGNMENT FRAMEWORK PROPERTIES
#***********************************************************************************
## ENTER THE NAME OF THE ORGANIZATIONAL ROLE CONTAINING BIRTHRIGHT BUSINESS ROLES
%%SP_BIRTHRIGHT_ROLES_ORGANIZATION_ROLE%%=Birthright Roles
## ENTER true/false FOR WHETHER TO ASSIGN A DEFAULT BIRTHRIGHT ROLE
%%SP_USE_DEFAULT_BIRTHRIGHT_ROLE%%=false
## ENTER THE NAME OF THE DEFAULT BIRTHRIGHT ROLE (ONLY USED IF ABOVE IS TRUE)
%%DEFAULT_SP_BIRTHRIGHT_ROLE%%=Default Birthright Role
#***********************************************************************************
# FEATURE PROPERTIES
#***********************************************************************************
#***********************************************************************************
# 	JOINER FEATURE PROPERTIES
#***********************************************************************************
## SPECIFY WHETHER DISABLED
%%SP_JOINER_IS_DISABLED%%=true
## SPECIFY WHETHER WORKFLOW TRACE IS ENABLED
%%SP_JOINER_WF_TRACE_ENABLED%%=false
## ENTER true/false ON WHETHER TO SEND DEFAULT APPROVED/REJECTED EMAILS
%%SP_JOINER_SEND_APPROVED_EMAILS%%=false
## ENTER true/false ON WHETHER TO SEND DEFAULT POST PROVISION EMAILS
%%SP_JOINER_SEND_POST_PROVISION_EMAILS%%=false
## ENTER true/false ON WHETHER TO RUN PROVISIONING IN THE FOREGROUND
%%SP_JOINER_FOREGROUND_PROVISIONING%%=false
#***********************************************************************************
# 	LEAVER FEATURE PROPERTIES
#***********************************************************************************
## SPECIFY WHETHER DISABLED
%%SP_LEAVER_IS_DISABLED%%=true
## SPECIFY WHETHER WORKFLOW TRACE IS ENABLED
%%SP_LEAVER_WF_TRACE_ENABLED%%=false
## ENTER true/false ON WHETHER TO SEND DEFAULT APPROVED/REJECTED EMAILS
%%SP_LEAVER_SEND_APPROVED_EMAILS%%=false
## ENTER true/false ON WHETHER TO SEND DEFAULT POST PROVISION EMAILS
%%SP_LEAVER_SEND_POST_PROVISION_EMAILS%%=false
## ENTER true/false ON WHETHER TO RUN PROVISIONING IN THE FOREGROUND
%%SP_LEAVER_FOREGROUND_PROVISIONING%%=false
%%SP_LEAVER_SUNSET_REQUEST_NAME%%=SP Leaver Sunset
%%SP_LEAVER_SUNSET_WF%%=SP Cust Sunset WF
%%SUNSET_SCHEDULE_SECONDS%%=7200
#***********************************************************************************
# 	ATTR SYNCH FEATURE PROPERTIES
#***********************************************************************************
## SPECIFY WHETHER DISABLED
%%SP_ATTR_SYNCH_IS_DISABLED%%=true
## SPECIFY WHETHER WORKFLOW TRACE IS ENABLED
%%SP_ATTR_SYNCH_WF_TRACE_ENABLED%%=false
## ENTER true/false ON WHETHER TO SEND DEFAULT APPROVED/REJECTED EMAILS
%%SP_ATTR_SYNCH_SEND_APPROVED_EMAILS%%=false
## ENTER true/false ON WHETHER TO SEND DEFAULT POST PROVISION EMAILS
%%SP_ATTR_SYNCH_SEND_POST_PROVISION_EMAILS%%=false
## ENTER true/false ON WHETHER TO RUN PROVISIONING IN THE FOREGROUND
%%SP_ATTR_SYNCH_FOREGROUND_PROVISIONING%%=false
#***********************************************************************************
# 	MOVER FEATURE PROPERTIES
#***********************************************************************************
## SPECIFY WHETHER DISABLED
%%SP_MOVER_IS_DISABLED%%=true
## SPECIFY WHETHER WORKFLOW TRACE IS ENABLED
%%SP_MOVER_WF_TRACE_ENABLED%%=false
## ENTER true/false ON WHETHER TO SEND DEFAULT APPROVED/REJECTED EMAILS
%%SP_MOVER_SEND_APPROVED_EMAILS%%=false
## ENTER true/false ON WHETHER TO SEND DEFAULT POST PROVISION EMAILS
%%SP_MOVER_SEND_POST_PROVISION_EMAILS%%=false
## ENTER true/false ON WHETHER TO RUN PROVISIONING IN THE FOREGROUND
%%SP_MOVER_FOREGROUND_PROVISIONING%%=false
#***********************************************************************************
# 	REHIRE FEATURE PROPERTIES
#***********************************************************************************
## SPECIFY WHETHER DISABLED
%%SP_REHIRE_IS_DISABLED%%=true
## SPECIFY WHETHER WORKFLOW TRACE IS ENABLED
%%SP_REHIRE_WF_TRACE_ENABLED%%=false
## ENTER true/false ON WHETHER TO SEND DEFAULT APPROVED/REJECTED EMAILS
%%SP_REHIRE_SEND_APPROVED_EMAILS%%=false
## ENTER true/false ON WHETHER TO SEND DEFAULT POST PROVISION EMAILS
%%SP_REHIRE_SEND_POST_PROVISION_EMAILS%%=false
## ENTER true/false ON WHETHER TO RUN PROVISIONING IN THE FOREGROUND
%%SP_REHIRE_FOREGROUND_PROVISIONING%%=false
#***********************************************************************************
# 	TERMINATE IDENTITY FEATURE PROPERTIES
#***********************************************************************************
## SPECIFY WHETHER DISABLED
%%SP_TERMINATE_IDENTITY_IS_DISABLED%%=true
## SPECIFY THE CATEGORY 
%%SP_TERMINATE_IDENTITY_LINK_CATEGORY%%=Admin
## SPECIFY HOW THE KEY FOR HOW THE LINK WILL BE DISPLAYED
%%SP_TERMINATE_IDENTITY_LINK_MESSAGE_KEY%%=Terminate Identity
## SPECIFY WHAT ORDER THE LINK WILL SHOW UP
%%SP_TERMINATE_IDENTITY_LINK_ORDERING%%=3
## SPECIFY WHETHER WORKFLOW TRACE IS ENABLED
%%SP_TERMINATE_IDENTITY_WF_TRACE_ENABLED%%=false
## ENTER true/false ON WHETHER TO SEND DEFAULT APPROVED/REJECTED EMAILS
%%SP_TERMINATE_IDENTITY_SEND_APPROVED_EMAILS%%=false
## ENTER true/false ON WHETHER TO SEND DEFAULT POST PROVISION EMAILS
%%SP_TERMINATE_IDENTITY_SEND_POST_PROVISION_EMAILS%%=false
## ENTER true/false ON WHETHER TO RUN PROVISIONING IN THE FOREGROUND
%%SP_TERMINATE_IDENTITY_FOREGROUND_PROVISIONING%%=false
#***********************************************************************************
# 	SST UNIT TESTER
#***********************************************************************************

### Workday PROPERTIES
%%WORKDAY_APP_NAME%%=Workday
## AD Connector Properties
%%MAQ_AD_APP_NAME%%=Maquarie
%%MAQ_AD_SERVER_IP%%=192.168.86.189
%%MAQ_AD_USER_SEARCH_DN%%=OU=Employees,OU=SailPoint,DC=maquarie,DC=com
%%MAQ_AD_GROUP_SEARCH_DN%%=OU=BusinessGroups,OU=SailPoint,DC=maquarie,DC=com
%%MAQ_AD_PASSWORD%%=1:ACP:XLXKP+kfAtgNgExeJN1A4K6JCsKYvxuNkqEmt5WbSXI=
%%MAQ_AD_FOREST_NAME%%=maquarie.com
%%MAQ_AD_USER%%=MAQUARIE\Administrator
%%MAQ_AD_DOMAIN%%=maquarie.com
%%AD_SERVER_IP%%=192.168.86.182
### Bundle-BR-Object-Names
%%BR_MAQ_APPLICATION_OWNER_NAME%%=BR-MAQ-ApplicationOwner
### Bundle-IT-Object-Names
%%IT_MAQ_APPLICATION_DESIGNER%%=IT-MAQ-ApplicationDesigner
%%IT_MAQ_APPLICATION_DEVELOPER%%=IT-MAQ-ApplicationDeveloper
%%IT_MAQ_APPLICATION_ENGINEER%%=IT-MAQ-ApplicationEngineer
%%IT_MAQ_APPLICATION_SUPPORT_ANALYST%%=IT-MAQ-ApplicationSupportAnalyst
### Bundle-ORG-Object-Names
%%ORG_MAQUARIE%%=MAQUARIE
%%ORG_MAQ_APPLICATION_OWNER%%=MAQ-ApplicationOwner
%%ORG_MAQ_BR_APPLICATION_OWNER%%=MAQ-BR-ApplicationOwner
%%ORG_MAQ_IT_APPLICATION_OWNER%%=MAQ-IT-ApplicationOwner
### AuthEmployees Application-Details ################################################
%%APP_AUTH_EMPLOYEES%%=AuthEmployees
%%APP_AUTH_EMPLOYEES_FILE_PATH%%=D:\csv_FIles\connectors_CSV\AuthEmployees.csv
### AuthContractors Application-Details ################################################
%%APP_AUTH_CONTRACTORS_APP_NAME%%=AuthContractors
%%APP_AUTH_CONTRACTORS_FILE_PATH%%=D:\csv_FIles\connectors_CSV\AuthContractors.csv
### Crunch-Time Application-Details ################################################
%%CRUNCH_TIME_APP_NAME%%=Crunch_Time
%%CRUNCH_TIME_CONCEPT_FILE_PATH%%=D:\csv_FIles\CrunchTime\Concept.csv
%%CRUNCH_TIME_GROUP_FILE_PATH%%=D:\csv_FIles\CrunchTime\Group.csv
%%CRUNCH_TIME_HIERARCHY_FILE_PATH%%=D:\csv_FIles\CrunchTime\Hierarchy.csv
%%CRUNCH_TIME_LOCATION_FILE_PATH%%=D:\csv_FIles\CrunchTime\Location.csv
%%CRUNCH_TIME_LOGICAL_NAME_FILE_PATH%%=D:\csv_FIles\CrunchTime\LogicalName.csv
%%CRUNCH_TIME_MARKET_FILE_PATH%%=D:\csv_FIles\CrunchTime\Market.csv
%%CRUNCH_TIME_APPLICATION_USERS_FILE_PATH%%=D:\csv_FIles\CrunchTime\ApplicationUsers.csv
%%CRUNCH_TIME_BUILD_MAP_RULE%%=CrunchTime-BuildMap Rule
### ServiceNow Application-Details ################################################
%%SERVICE_NOW_USERS_FILE_NAME%%=serviceNow
%%SERVICE_NOW_USERS_FILE_PATH%%=D:\csv_FIles\connectors_CSV\serviceNow.csv
### Workday Application-Details 
################################################
%%WORKDAY_APP_NAME%%=Workday
%%WORKDAY_USERS_FILE_PATH%%=D:\csv_FIles\connectors_CSV\Workday.csv
### Finance Application-Details
################################################
%%FINANCE_USERS_FILE_NAME%%=Finance-users
%%FINANCE_USERS_FILE_PATH%%=D:\csv_FIles\connectors_CSV\Finance-users.csv
### Eshiam Application-Details
################################################
%%ESHIAM_AD_APP_NAME%%=Eshiam
%%ESHIAM_AD_SERVER_IP%%=192.168.86.189
%%ESHIAM_AD_USER_SEARCH_DN%%=OU=Employees,OU=SailPoint,DC=eshiam,DC=com
%%ESHIAM_AD_GROUP_SEARCH_DN%%=OU=BusinessGroups,OU=SailPoint,DC=eshiam,DC=com
%%ESHIAM_AD_PASSWORD%%=1:ACP:XLXKP+kfAtgNgExeJN1A4K6JCsKYvxuNkqEmt5WbSXI=
%%ESHIAM_AD_FOREST_NAME%%=eshiam.com
%%ESHIAM_AD_USER%%=ESHIAM\Administrator
%%ESHIAM_AD_DOMAIN%%=eshiam.com
%%AD_SERVER_IP%%=192.168.86.185